### ISSUE TITLE
the pretrained models can not be downloaded

### ISSUE THREAD

**Issue by zkself** [computationalmedia/semstyle#5]
hello, i am very appreciate with your nice work.
after  i  run the download.sh file,the model can not be downloaded.
i also tried the browser method,but it didn't work.
and then ,i tried uget and it didn't work too.
by the way, i can cross the GFW.

**Comment by almath123** [comment]
I think there were/are some technical issues on our end. For the time being I have switched to a different hosting location. You will have to download the files from the new locations manually (see new download.sh). Please let me know if it works/does not work.

**Comment by zkself** [comment]
it works!
i will close this issue.
thank you

**Comment by zkself** [comment]
@almath123  the tar file cannot be decompressed.
i use chrome to download the file.
the postfix of tar.gz/zip/rar also didn't work.

the mistake info are listed below:

zkself@zkself-ubuntu:~/Downloads$ tar -xvf img_to_txt_state.tar 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

**Comment by almath123** [comment]
@zkself The tar file is a serialised model file generated by pytorch, you don't need to decompress it. pytorch should do that. Note how the code directly references the models as ".tar" files.

**Comment by zkself** [comment]
@almath123  OK, i am sorry for my naive question :)

**Comment by almath123** [comment]
@zkself Not to worry, it was a reasonable question, I have made exactly the same mistake before.
