### ISSUE TITLE
question about pyreadability and edit_distance

### ISSUE THREAD

**Issue by marzi-heidari** [computationalmedia/semstyle#8]
I have a weird problem in importing pyreadability which I already asked [here in stackoverflow](https://stackoverflow.com/questions/54265749/importerror-no-module-named-pyreadability-in-conda-env). Also a similar problem with edit_distance (I've installed package edit_distance using:
`conda install -c conda-forge edit_distance`
but getting: 
`ImportError: cannot import name EditDistance`)
I'm starting to think these packages are not the ones I thought and maybe these classes are implemented by you that for some reason not included in the repository and just have similar names to python packages that are available to install.
Is that so?

**Comment by almath123** [comment]
Hmm. I should have included those files.
I have added the edit_distance.py file.
I think that pyreadability is my implementation which is available here: https://github.com/almath123/pyreadability

**Comment by marzi-heidari** [comment]
Thank you for your attention to my questions. I really appreciate your prompt responses and  action for adding codes
